### ISSUE TITLE
Add FRONT_CONTROLLER_FILE for nginx configuration

### ISSUE THREAD

**Issue by bshaffer** [GoogleCloudPlatform/php-docker#151]
Often we have to create an `nginx-app.conf` file just to change the name of the front controller. Some frameworks use `index.php`, some use `app.php`, etc.

We could introduce another envvar like `FRONT_CONTROLLER_FILE`, so that you can do:

app.yaml

``` yaml
runtime: php
vm: true

runtime_config:
  document_root: web

env_variables:
  WHITELIST_FUNCTIONS: libxml_disable_entity_loader
  FRONT_CONTROLLER_FILE: app.php
```

see https://github.com/GoogleCloudPlatform/php-docs-samples/pull/190

**Comment by tmatsuo** [comment]
I think it's more consistent if we do this in the `runtime_config` as follows:

```
runtime: php
env: flex

runtime_config:
  document_root: web
  front_controller: app.php
```

@bshaffer WDYT?

**Comment by chingor13** [comment]
The `runtime_config` section seems like a better place to have a contract with the user. It will give us the flexibility to handle it at build time or run time (but preferably at build time).

**Comment by tmatsuo** [comment]
Now we can use environment variables in nginx.conf, so maybe we can just pass it as an env var. But stil I prefer having it in `runtime_confg`. It's easy to understand if `runtime_config` is where you configure our runitme. `env_variables` is for controlling your app's behavior.

**Comment by tmatsuo** [comment]
Now it's supported by the new builder pipeline.
The simple sample:
```
runtime: php
env: flex

runtime_config:
  document_root: web
  front_controller: app.php
```

To use the builder pipeline, you have to
- set `app/use_runtime_builders` to true by `gcloud config set app/use_runtime_builders true`
- use `gcloud beta app deploy` for deploying
