### ISSUE TITLE
Apache Support

### ISSUE THREAD

**Issue by bshaffer** [GoogleCloudPlatform/php-docker#205]
Allow the option to use Apache instead of NGINX as the web server. This could be done by exposing a `runtime_config.server` option in `app.yaml`.

```yaml
runtime:  php
env: flex
runtime_config:
  server: apache
```

The runtime would also load an optional `apache-app.conf` in the root of the project to allow apache custom config.
