### ISSUE TITLE
epoll_wait() reported that client prematurely closed connection

### ISSUE THREAD

**Issue by TriPSs** [GoogleCloudPlatform/php-docker#443]
When running this image in GKE my pods won't go into the ready state as the call who checks if they are ready fails.

Logs
```
api | 21 May 2018, 21:54:21 | 2018/05/21 19:54:21 [info] 43#0: *3 epoll_wait() reported that client prematurely closed connection, so upstream connection is closed too while sending request to upstream, client: 10.8.12.1, server: , request: "GET /alive HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "10.8.12.6:8080"
-- | -- | --
api | 21 May 2018, 21:54:21 | 10.8.12.1 - - [21/May/2018:19:54:21 +0000] "GET /alive HTTP/1.1" 499 0 "-" "kube-probe/1.9+"
api | 21 May 2018, 21:54:19 | 10.8.12.1 - - [21/May/2018:19:54:19 +0000] "GET /alive HTTP/1.1" 499 0 "-" "kube-probe/1.9+"
api | 21 May 2018, 21:54:19 | 2018/05/21 19:54:19 [info] 43#0: *1 epoll_wait() reported that client prematurely closed connection, so upstream connection is closed too while sending request to upstream, client: 10.8.12.1, server: , request: "GET /alive HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "10.8.12.6:8080"
api | 21 May 2018, 21:54:14 | 2018-05-21 19:54:14,464 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
api | 21 May 2018, 21:54:14 | 2018-05-21 19:54:14,464 INFO success: php-fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
api | 21 May 2018, 21:54:13 | [21-May-2018 19:54:13] NOTICE: ready to handle connections
api | 21 May 2018, 21:54:13 | [21-May-2018 19:54:13] NOTICE: fpm is running, pid 41
api | 21 May 2018, 21:54:13 | 2018/05/21 19:54:13 [notice] 42#0: start worker process 44
api | 21 May 2018, 21:54:13 | 2018/05/21 19:54:13 [notice] 42#0: start worker process 43
api | 21 May 2018, 21:54:13 | 2018/05/21 19:54:13 [notice] 42#0: start worker processes
api | 21 May 2018, 21:54:13 | 2018/05/21 19:54:13 [notice] 42#0: getrlimit(RLIMIT_NOFILE): 1048576:1048576
api | 21 May 2018, 21:54:13 | 2018/05/21 19:54:13 [notice] 42#0: OS: Linux 4.4.111+
api | 21 May 2018, 21:54:13 | 2018/05/21 19:54:13 [notice] 42#0: nginx/1.6.2
api | 21 May 2018, 21:54:13 | 2018/05/21 19:54:13 [notice] 42#0: using the "epoll" event method
api | 21 May 2018, 21:54:13 | 2018-05-21 19:54:13,411 INFO spawned: 'nginx' with pid 42
api | 21 May 2018, 21:54:13 | 2018-05-21 19:54:13,409 INFO spawned: 'php-fpm' with pid 41
api | 21 May 2018, 21:54:12 | 2018-05-21 19:54:12,407 INFO supervisord started with pid 1
api | 21 May 2018, 21:54:12 | 2018-05-21 19:54:12,405 CRIT Supervisor running as root (no user in config file)
api | 21 May 2018, 21:54:12 | + exec /usr/bin/supervisord -c /etc/supervisor/supervisord.conf
api | 21 May 2018, 21:54:12 | Locking down the document root...
api | 21 May 2018, 21:54:12 | + /bin/bash /build-scripts/lockdown.sh
api | 21 May 2018, 21:54:12 | + grep -q post-deploy-cmd
api | 21 May 2018, 21:54:12 | + su www-data -c 'php /usr/local/bin/composer --no-ansi run-script -l'
api | 21 May 2018, 21:54:12 | + '[' -f /app/composer.json ']'
api | 21 May 2018, 21:54:12 | + '[' -n '' ']'
api | 21 May 2018, 21:54:12 | nginx: configuration file /etc/nginx/nginx.conf test is successful
api | 21 May 2018, 21:54:12 | nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
api | 21 May 2018, 21:54:12 | + /usr/sbin/nginx -t -c /etc/nginx/nginx.conf
api | 21 May 2018, 21:54:12 | + /bin/bash /build-scripts/move-config-files.sh
api | 21 May 2018, 21:54:12 | Moving user supplied config files...
cloudsql-proxy | 21 May 2018, 21:53:14 | 2018/05/21 19:53:14 Ready for new connections
cloudsql-proxy | 21 May 2018, 21:53:14 | 2018/05/21 19:53:14 Listening on 127.0.0.1:3306 for xxxxx
cloudsql-proxy | 21 May 2018, 21:53:14 | 2018/05/21 19:53:14 using credential file for authentication; 

```

**Comment by chingor13** [comment]
Thanks for the report.

Can you a bit more information about your setup? i.e. which docker image you are referring to and any relevant kubernetes config (liveness settings)

**Comment by TriPSs** [comment]
My deployment:
```
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 40%
      maxUnavailable: 0% 

  template:
    metadata:
      labels:
        app: api

    spec:
      tolerations:
      - operator: "Exists"
      containers:
        - name: api
          image: gcr.io/xxx/api:latest
          ports:
            - containerPort: 8080

          resources:
            requests:
              memory: "50Mi"
              cpu: "200m"
            limits:
              memory: "150Mi"
              cpu: "600m"

          livenessProbe:
            httpGet:
              path: /alive
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 20

          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /alive
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 2
            successThreshold: 1
            timeoutSeconds: 1

          envFrom:
            - configMapRef:
                name: api-config

          env:
            - name: DB_HOST
              value: 127.0.0.1:3306

            - name: DB_NAME
              value: api

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: api-db-credentials
                  key: username

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: api-db-credentials
                  key: password

            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName

        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.11
          command: ["/cloud_sql_proxy",
                    "-instances=xxxx=tcp:3306",
                    "-credential_file=/secrets/service-accounts/api.json"]
          volumeMounts:
            - name: service-accounts-credentials
              mountPath: /secrets/service-accounts
              readOnly: true

      volumes:
        - name: service-accounts-credentials
          secret:
            secretName: service-accounts-credentials
            items:
            - key: api.json
              path: api.json

        - name: cloudsql
          emptyDir:

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: api-scaler
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: api
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 75
```

The docker file
```
# Dockerfile extending the generic PHP image with application files for a
# single application.
FROM gcr.io/google_appengine/php:latest

ENV DOCUMENT_ROOT=/app/public
ENV IS_BATCH_DAEMON_RUNNING=true

ARG GKE_VERSION
ENV GKE_VERSION=$GKE_VERSION
```
