### ISSUE TITLE
There is no existing directory at "/var/log/app_engine" and its not buildab  

### ISSUE THREAD

**Issue by Bonfante** [GoogleCloudPlatform/php-docker#452]
This error when deploying an symfony 4 to app engine using memorystore to system cache
cache and monolog config
```
framework:
        cache:
                app: cache.adapter.redis
                system: cache.adapter.redis
                default_redis_provider: "redis://%env(resolve:REDIS_HOST)%:%env(resolve:REDIS_PORT)%"
monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_404s:
                # regex: exclude all 404 errors from the logs
                - ^/
        nested:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type:   console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
        cloud:
            type: service
            id: 'Google\Cloud\Core\Logger\AppEngineFlexHandler'
            level: debug
```

```
Step #1: ocramius/package-versions: ...done generating version class
Step #1: Executing script cache:clear [KO]
Step #1:  [KO]
Step #1: Script cache:clear returned with error code 1
Step #1: !!  
Step #1: !!  In StreamHandler.php line 171:
Step #1: !!                                                                                 
Step #1: !!    There is no existing directory at "/var/log/app_engine" and its not buildab  
Step #1: !!    le: Permission denied                                                        
Step #1: !!                                                                                 
Step #1: !!  
Step #1: !!  
Step #1: Script @auto-scripts was called via post-install-cmd
Step #1: The command '/bin/sh -c /build-scripts/composer.sh' returned a non-zero code: 1
Finished Step #1
ERROR
ERROR: build step 1 "gcr.io/cloud-builders/docker@sha256:9635fb8af170fc70187d1ce23155ad5c45aa7b12840505c8d988a65c1640d027" failed: exit status 1
Step #1: 

```

may relate to this, at least the error seems to be equal
https://github.com/GoogleCloudPlatform/google-cloud-python/pull/3410
https://github.com/GoogleCloudPlatform/google-cloud-python/issues/2997
