### ISSUE TITLE
Laravel 8 - build failed in google app engine flexible environment

### ISSUE THREAD

**Issue by bhaidar** [GoogleCloudPlatform/php-docker#534]
Hello,
I have a Laravel PHP app with the following:

- app.yaml
```
runtime: php
env: flex

runtime_config:
document_root: public
whitelist_functions: proc_open
automatic_scaling:
min_num_instances: 1
max_num_instances: 1
resources:
cpu: 1
memory_gb: 0.5
disk_size_gb: 10
env_variables:
# See substitution variables for Google Cloud Build Trigger
```

- cloud_build.yaml
```
steps:
  - name: node:14.0.0
    entrypoint: npm
    args: ['install']
  - name: node:14.0.0
    entrypoint: npm
    args: ['run', 'prod']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', '--project', '$PROJECT_ID', '-q', '$_GAE_PROMOTE', '-v', '$_GAE_VERSION']
timeout: '3600s'
```

- composer.json
```
"require": {
"php": "7.3.*",
...
}
```

When the Cloud Build Trigger runs, I get the following error:

```
Step #0: Digest: sha256:1f43a583e4c10b1758647be47b9fb5f9659227ef266978694acbb7981e4ee093
Step #0: Status: Downloaded newer image for gcr.io/gcp-runtimes/php/gen-dockerfile@sha256:1f43a583e4c10b1758647be47b9fb5f9659227ef266978694acbb7981e4ee093
Step #0: gcr.io/gcp-runtimes/php/gen-dockerfile@sha256:1f43a583e4c10b1758647be47b9fb5f9659227ef266978694acbb7981e4ee093
Step #0: + php /builder/create_dockerfile.php create --php73-image gcr.io/google-appengine/php73@sha256:bee53597a0df4167547fd9c2a501484e8c5d03831298f50c1db0e9cdcd915a88 --php72-image gcr.io/google-appengine/php72@sha256:c3f3636b89aab3a83ab288a0108f767a4d56002c9a214b17b5fe93b9ba5f8bbf --php71-image gcr.io/google-appengine/php71@sha256:9d39f66c4e0b7c9a9590ed27373b8c18e79a6cde3dbf48c284ffc5f3fd99d12a
Step #0: [09-Jun-2021 19:06:00 UTC] PHP Warning: array_key_exists() expects parameter 2 to be array, null given in /builder/src/Builder/GenFilesCommand.php on line 232
Step #0:
Step #0: Warning: array_key_exists() expects parameter 2 to be array, null given in /builder/src/Builder/GenFilesCommand.php on line 232
Step #0: [09-Jun-2021 19:06:00 UTC] PHP Warning: array_key_exists() expects parameter 2 to be array, null given in /builder/src/Builder/GenFilesCommand.php on line 232
Step #0:
Step #0: Warning: array_key_exists() expects parameter 2 to be array, null given in /builder/src/Builder/GenFilesCommand.php on line 232
Step #0: [09-Jun-2021 19:06:00 UTC] PHP Warning: array_key_exists() expects parameter 2 to be array, null given in /builder/src/Builder/GenFilesCommand.php on line 174
Step #0:
Step #0: Warning: array_key_exists() expects parameter 2 to be array, null given in /builder/src/Builder/GenFilesCommand.php on line 174
Step #0: [09-Jun-2021 19:06:00 UTC] PHP Fatal error: Uncaught Error: Unsupported operand types in /builder/src/Builder/GenFilesCommand.php:279
```
